# Generated by Django 2.2.12 on 2021-09-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=200, verbose_name='DNI')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del alumno')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción del certificado')),
                ('observation', models.TextField(verbose_name='Observación')),
                ('published', models.DateTimeField(verbose_name='Fecha de publicación')),
            ],
        ),
    ]
